### ISSUE TITLE
allow time rating without hit completion(?)

### ISSUE THREAD

**Issue by toutils** [turkopticon/turkopticon-rails-app#40]
This goes along with what I mentioned here:
https://turkopticon.ucsd.edu/forum/show_post/1558

and an example of this came up when I was trying to transfer reviews to the new site.
https://turkopticon.info/requesters/A2ZH21CP28SHAM

One of these hits literally paid $25/hr. Another one was posted that paid $2.25 and required watching a 33 minute video right off the bat. I and I imagine a lot of people returned it at that point. Because of the way the rating system works, api calls for this requester are going to show $25/hr, when that's clearly not the case, and I'm sure this won't be an isolated thing.

When you click "I didn't finish the hit" it grays out the time field. I can see where there's justification for this, but it's going to end up skewing pay rates higher than they should be. I'd like to suggest allowing people to enter a time even if they didn't finish the hit. If the goal is to prevent people rating hits they didn't do, someone could easily just claim they did it.

**Comment by zihel** [comment]
From turkopticon-discuss:
> If someone spends 10 minutes on a survey and then is forced to return it, should they enter $0 for the hit reward, and 10 minutes for the hit time? or should they just mark "I didn't finish the HIT." and leave the hit reward blank? 

No, please don't do any of that. That is considered falsifying information which negatively impacts data integrity when we are moving away from a purely subjective system. The recommendation field is very useful and can be used as a catchall for this kind of situation. 

The API returns much more than the pay rate. If users see a requester with a high pay rate but notice only a small fraction of people would recommend their HITs, then that's cause for suspicion. They can then immediately choose to discard that HIT or investigate further by clicking through and actually reading the reviews before making their decision.

There will always be users who misuse any given system, maliciously or otherwise, and hopefully moderators can deal with them, but encouraging people to manipulate the database or report a completion time when they did not complete a HIT is not the answer here.

**Comment by toutils** [comment]
Ya that makes sense. I can imagine when hitscraper or others eventually integrate this, you'd see a high pay rate and red to indicate low recommendations and/or rejects, weighted or something, that would actually work pretty well.

This new hitform is much more self explanatory, I'm sure it was written to avoid having to write excessive guidelines, but I think they should still be there somewhere to cover this type of situation and others that come up.
