### ISSUE TITLE
allow rating approval / rejection without time, add auto approval(?)

### ISSUE THREAD

**Issue by toutils** [turkopticon/turkopticon-rails-app#42]
Another issue I'm coming across, 

"Approximately how long did it take to approve or reject?" is required to rate
"How much of your work was rejected?"

I write reviews immediately after doing a hit, and then usually come back and rate it as approved (fair scale on old TO), assuming it doesn't reject. I think that's a common way to do it. I try to mention the auto approval time in the review though. 

I can't speak for everyone but I don't think real approval / rejection times are a stat a lot of people keep for every single hit they do. I could come up with a number, but it wouldn't be accurate to the exact day, it's not something HitDB tracks.

I'd suggest allowing people to rate "How much of your work was rejected?", and make the time optional, otherwise it's going to get left unrated or people are just going to enter an inaccurate time if they don't have it.

My inclination is to punch in the auto approval time and mark it as "none" for rejected, but a lot of hits are processed before the auto-approval. It would be nice to have a separate box for that.

**Comment by zihel** [comment]
Both of the time fields (completion and pending) are tricky because neither are stats too many people track with any high amount of accuracy; that's why we ask for an approximation. Of course the more accurate the better, but in most cases, (almost) anything is better than nothing. The important thing to remember is that for both fields, people are generally looking for a ballpark more than high precision anyways.

If a HIT approved before the auto-approval time, it would be better to have any sort of estimate than just the auto-approval time.
