### ISSUE TITLE
reward doesn't get get passed correctly in url for new review

### ISSUE THREAD

**Issue by toutils** [turkopticon/turkopticon-rails-app#47]
Here's an example of this:
https://turkopticon.info/reviews/new?rid=A2DPU6JE37X0YV&name=Speechfeedback&title=Rate%20the%20quality%20of%20computer-generated%20speech%20-%20English@United%20States%20native%20only%20[#9cbe]&reward=0.60

"reward" is passed but doesn't get applied to the reward field

**Comment by toutils** [comment]
also this doesn't happen every time, this has only happened occasionally, and the url is generated from turkoscript

**Comment by zihel** [comment]
Oh this is due to a bug in the script not properly encoding the URL. The hash is interpreted as the beginning of a hash fragment which signifies the end of the query string.

Since this is a script bug, I'm closing this here. Please open an issue on the [script repository](https://github.com/turkopticon/turkoptiscript). Thanks.
